# https://taskfile.dev

version: '3'

tasks:
  default:
    desc: List all tasks
    cmds:
      - task --list-all
  run:
    desc: Run the application
    cmds:
      - uv run python main.py {{.CLI_ARGS}}
