"""Create generation_history and characters tables with improved schema

Revision ID: 1c55dba4dd75
Revises: 
Create Date: 2025-12-27 23:37:42.513459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c55dba4dd75'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('nickname', sa.String(length=200), nullable=True),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.Column('personality', sa.Text(), nullable=False),
    sa.Column('speech_style', sa.JSON(), nullable=False),
    sa.Column('reference_images', sa.JSON(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('generation_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('character_name', sa.String(length=100), nullable=False),
    sa.Column('input_topic', sa.Text(), nullable=False),
    sa.Column('generated_title', sa.String(length=100), nullable=False),
    sa.Column('image_data', sa.LargeBinary(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_created_at', 'generation_history', ['created_at'], unique=False)
    op.create_index('idx_status', 'generation_history', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_status', table_name='generation_history')
    op.drop_index('idx_created_at', table_name='generation_history')
    op.drop_table('generation_history')
    op.drop_table('characters')
    # ### end Alembic commands ###
